### ISSUE TITLE
Ausência do txid

### ISSUE THREAD

**Issue by jocimarcan** [NascentSecureTech/pix-qrcode-utils#1]
Primeiro, parabéns pela iniciativa!
Ao gerar QR code pelo https://pix.nascent.com.br/tools/pix-qr-decoder/ o txid não está sendo incluído na string do QR code quando não preenchido.
Quando o txid não é preenchido, ele deve ser preenchido com ***, uma vez que é um campo obrigatório no BR Code.

**Comment by cryptographix** [comment]
@jocimarcan corrigido pela inclusão do valor default, tanto para estático como dinâmico. Já tá live. 

Quaisquer dúvidas, sugestões para melhorias e novas funcionalidade, pode mandar. Valeu!

**Comment by MarceloPrado** [comment]
@jocimarcan já dá pra fechar esta issue, não?

**Comment by jocimarcan** [comment]
Obrigado, SeanWykes!
Dá sim @MarceloPrado. Acabei esquecendo
