### ISSUE TITLE
Campo Merchant City não valida tamanho máximo.

### ISSUE THREAD

**Issue by guiscota** [NascentSecureTech/pix-qrcode-utils#2]
Olá, pessoal. Desde já gostaria de parabenizá-los pelo projeto!
Utilizando o [decoder](https://pix.nascent.com.br/tools/pix-qr-decoder), o campo Merchant City não está validando o tamanho máximo, que é 15 conforme [ManualBRCode](https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf), como podem ver [neste exemplo](https://gnetbr.com/HylSWLzB5u).

**Comment by cryptographix** [comment]
Olá Guilherme,

Obrigado pelo relato. Se tiver outros campos sem validação, por favor me avise e incluo as validações todas na próxima versão.

Caso tiver interesse no código, o esquema de validação está no: [element-scheme.ts](https://github.com/NascentSecureTech/pix-qrcode-utils/blob/820f3200b3a0cb45fc576ef6913accba4d2bdadb/packages/emv-merchant-qrcode/src/element-scheme.ts)

Abraços .. Sean

**Comment by guiscota** [comment]
Pelo que analisei, é somente este campo mesmo que deixou passar.

Mais uma vez, obrigado.
Abraço Sean!
